### ISSUE TITLE
is.redundant returns the inverse of what its documentation implies

### ISSUE THREAD

**Issue by brisbia** [mhahsler/arules#11]
Hello,

The documentation (and function name) of is.redundant suggests that it should return TRUE for rules that are redundant, i.e. rules that have a negative improvement.  Instead, it returns TRUE for rules with a positive improvement.

Thanks!

**Comment by mhahsler** [comment]
Thanks for the bug report! This is now fixed in the development version on github. It will be part of the next CRAN release version 1.4-2.
