### ISSUE TITLE
Association rules in R (arules) - how to use the dissimilarity function in arules R

### ISSUE THREAD

**Issue by leih123** [mhahsler/arules#13]
I am trying to do association rules clustering in R and I am having a problem when I was trying to use the function "dissimilarity". I tried something like this:

`dis<-dissimilarity(rules, method = "gupta", args = "trans")`

I want to use the "gupta" method to calculate the dissimilarity/distances of the rules, the R help manual said to use "gupta": **"The transactions used to mine the associations has to be passed on via args as element "transactions"."**

"trans" is my transactions (sparse format) and "rules" is my association rules. An error message said _"Error in args$$trans : $ operator is invalid for atomic vectors"_

why is it doesn't work?

I have also tried:

 `dis<-dissimilarity(rules, method = "gupta", args = list("trans"))`

Error: _Error in .local(x, y, method, args, ...) : Transactions needed in args for this method!_

Is there anything wrong with my syntax?

HELP PLEASE !!!!!!!!!!

**Comment by mhahsler** [comment]
Let's assume your transactions are called Groceries then the syntax is:

     dis <- dissimilarity(rules, method = "gupta", args = list(transactions = Groceries))

**Comment by leih123** [comment]
It works, thanks!!
