### ISSUE TITLE
Something wrong with the is.redundant function

### ISSUE THREAD

**Issue by leih123** [mhahsler/arules#14]
I was trying to remove redundant rules from my association rules (total 3xxx rules) and after the use of the `is.redundant` function:
`inspect(rules[!is.redundant(rules)])`
It turns out just 54 rules are not redundant. I was quite shock, and then I used another example to test which is here: http://www.rdatamining.com/examples/association-rules 
The redundant rules, as shown, should be rules [2], [4], [7], and [8], but I used the `is.redundant` function and it showed that only rules [4] and [8] are NOT redundant which is totally wrong apparently.

Is there anything wrong with the function or have I misused it?

**Comment by leih123** [comment]
I have seen some of your posts, is there a new version of arules released to fix this problem?

**Comment by mhahsler** [comment]
This should be fixed in version arules_1.4-2 which was released yesterday... Let me know if you find problems with it.

Thanks,
Michael

**Comment by leih123** [comment]
Thanks for your information!

I have tried and it treated rules `[4]` and `[8]` as redundant, but rules `[2]` and `[7]` are still non-redundant. Does it because of they have the same confidence as their "more general rule" `[1]` and `[6]` ? Is there any way that I can take them out of my rules as well?

If I have 2 rules for instance, {A, B} -> {C} and {A,C} -> {B}, can the `is.redundant` function detect them and treat one of them as redundant?

Thank you very much!!

**Comment by mhahsler** [comment]
> I have tried and it treated rules [4] and [8] as redundant, but rules [2] and [7] are still non-redundant. Does it because of they have the same confidence as their "more general rule" [1] and [6] ? Is there any way that I can take them out of my rules as well?

This is correct. In the current version of arules, rules with the same confidence are not removed. However, I have changed this behavior in the development version on github.

> If I have 2 rules for instance, {A, B} -> {C} and {A,C} -> {B}, can the is.redundant function detect them and treat one of them as redundant?

`is. redundant` only considers rules with the same consequent.

**Comment by leih123** [comment]
Thank you!!
