### ISSUE TITLE
R version dependency

### ISSUE THREAD

**Issue by dashaub** [mhahsler/arules#15]
Is there a code change between v1.2.x and 1.4.x that requires R >= 3.2.0? Lots of users run older releases of R for some time between updating, so if there isn't a vital new feature or bugfix required in the newer R releases a lower version dependency is nice--not necessarily 2.14, but R >= 3.0 represents a hard break.

**Comment by mhahsler** [comment]
Unfortunately there is a change in how the Matrix package is used in arules. Although Matrix does not need R 3.2.0 by itself, the dispatching mechanism for only works as expected in this higher R version.

From the NEWS:
# Changes in version 1.3-1 (12/13/2015)
* we now require R 3.2.0 so cbind in Matrix works.

**Comment by dashaub** [comment]
Fair enough, we can keep using the older version (using it as a dependency for "recommenderlab", great package btw). How about including the NEWS in CRAN releases? This was the first place I went to look to answer this question, but since it didn't appear on CRAN I didn't see it. CRAN will display the md file if it is placed in `inst/NEWS.md`

**Comment by mhahsler** [comment]
Seems like the existing NEWS file was excluded when building the package. This is now fixed and the next version should show it correctly on CRAN.
