### ISSUE TITLE
Unable to use '%pin%' on 'lhs'

### ISSUE THREAD

**Issue by gdbassett** [mhahsler/arules#16]
After running:
```
      rules <- df %>%
               apriori(appearance = list(lhs = c(x), default="rhs"), 
                       parameter=list(support=0.0, confidence=0.25))
```
When running the following line:
`rules <- subset(rules, subset = (lhs %pin% as.character(x)) & lift > 1)`
I receive the error:
`"unable to find an inherited method for function '%pin%' for signature '"standardGeneric", "character"'"`
I believe the 'standardGeneric is the 'lhs' portion and the portion causing the error.  x is just a column name.

This is with version 1.4-2.  I don't believe I received the error on version 1.4-1.

**Comment by mhahsler** [comment]
I cannot reproduce the error on either the CRAN version or the development version.

    library(arules)
    data(Groceries)
    rules <- apriori(Groceries, 
       parameter=list(support=0.001, confidence=0.8))
    x <- 'milk'
    rules <- subset(rules, subset = (lhs %pin% as.character(x)) & lift > 1)
    rules

    set of 63 rules 

Please send me the data and the exact code that produces the error.

**Comment by gdbassett** [comment]
The data set is proprietary but I can probably provide you a rules object that fails.  Would that work?

**Comment by mhahsler** [comment]
Yes, it would be great if you can modify my code from above so that it fails.

**Comment by gdbassett** [comment]
I tried duplicating with a dataset I could share and failed, however it fails consistently with the private data set.  It failed under versions 1.4-1, 1.4-2, and 1.4-2-1.  I can provide a failed rules object and will continue to try and replicate from scratch with a public dataset.  Is 'standardGeneric' the appropriate class for 'lhs' (or possibly the rules file in general) or should it be something else?

**Comment by gdbassett** [comment]
interestingly if I remove the `(lhs %pin% as.character(x)) &` portion of the subset, I receive the error `"object 'lift' not found"`.

**Comment by mhahsler** [comment]
I am pretty sure that this is your problem:

    rules <- 10
    subset(rules, subset = (lhs %pin% as.character(x)) & lift > 1)
    Show Traceback
 
    Rerun with Debug
    Error in (function (classes, fdef, mtable)  : 
    unable to find an inherited method for function ‘%pin%’ for signature ‘"standardGeneric", "character"’ 

In other words, rules does not contain rules and R unfortunately says this not in a very readable way.

**Comment by mhahsler** [comment]
This is strange. Does everything also look ok if you say inspect(rules)?

**Comment by gdbassett** [comment]
inspect(rules) looks normal:
```
##    lhs                                 rhs                                                       support confidence     lift
## 1  {}                               => {victim.employee_count.Unknown}                         0.2534307  0.2534307 1.000000
## 2  {}                               => {attribute.confidentiality.data.variety.Personal}       0.3153787  0.3153787 1.000000
## 3  {}                               => {attribute.confidentiality.data.variety.Unknown}        0.3827941  0.3827941 1.000000
## 4  {}                               => {actor.external.variety.Unknown}                        0.4337762  0.4337762 1.000000
## 5  {}                               => {asset.variety.Unknown}                                 0.4582470  0.4582470 1.000000
## 6  {}                               => {asset.assets.variety.Unknown}                          0.4582470  0.4582470 1.000000
## 7  {}                               => {actor.internal.variety.Unknown}                        0.4863627  0.4863627 1.000000
## 8  {}                               => {attribute.confidentiality.data_disclosure.Potentially} 0.5349928  0.5349928 1.000000
## 9  {}                               => {victim.employee_count.Large}                           0.7320986  0.7320986 1.000000
## 10 {}                               => {victim.industry2.92}                                   0.7357903  0.7357903 1.000000
## 11 {}                               => {victim.orgsize.Large}                                  0.7384539  0.7384539 1.000000
## 12 {asset.assets.variety.P - Other} => {pattern.Everything Else}                               0.1335846  0.8854016 6.396792
## 13 {asset.assets.variety.P - Other} => {action.social.variety.Phishing}                        0.1487095  0.9856494 6.607947
## 14 {asset.assets.variety.P - Other} => {action.social.vector.Email}                            0.1486939  0.9855461 6.515403
## 15 {asset.assets.variety.P - Other} => {asset.variety.Person}                                  0.1508746  1.0000000 6.497874
## 16 {asset.assets.variety.P - Other} => {attribute.integrity.variety.Alter behavior}            0.1508590  0.9998968 6.480151
## 17 {asset.assets.variety.P - Other} => {actor.external.variety.Unknown}                        0.1360769  0.9019203 2.079229
## 18 {asset.assets.variety.P - Other} => {victim.employee_count.Large}                           0.1265752  0.8389428 1.145942
## 19 {asset.assets.variety.P - Other} => {victim.industry2.92}                                   0.1270736  0.8422465 1.144683
## 20 {asset.assets.variety.P - Other} => {victim.orgsize.Large}                                  0.1267465  0.8400785 1.137618
```

**Comment by gdbassett** [comment]
The only odd thing is the 1<->1 mapping. I can't remember if that's an artifact of how I ran apriori or an anomaly.

**Comment by mhahsler** [comment]
did you put the inspect right before the subset in the original code that creates the error (the markdown file)?

**Comment by gdbassett** [comment]
The inspect is immediately after the subset, however the subset is commented out.  (It would get rid of the empty LHS's if it were working.)

**Comment by mhahsler** [comment]
This is really strange. Try to replace the subset with this:

     rules[lhs(rules) %pin% as.character(x) & quality(rules)$lift>1]

Also, do you load a package that overwrites %pin%?

**Comment by gdbassett** [comment]
It's possible that %pin% is being overwritten as I load a bunch of stuff, however I tried removing it and still received an error that 'lift' didn't exist.  I also directly defined %pin% (`\`%pin%\` <- arules::\`%pin%\`` and still received the error.

Technically I used `rules <- rules[lhs(rules) %pin% as.character(x) & quality(rules)$lift>1]`, but that worked.  Received no errors and received the filtered output:
##   lhs                                 rhs                                            support confidence     lift
## 1 {asset.assets.variety.P - Other} => {pattern.Everything Else}                    0.1335846  0.8854016 6.396792
## 2 {asset.assets.variety.P - Other} => {action.social.variety.Phishing}             0.1487095  0.9856494 6.607947
## 3 {asset.assets.variety.P - Other} => {action.social.vector.Email}                 0.1486939  0.9855461 6.515403
## 4 {asset.assets.variety.P - Other} => {asset.variety.Person}                       0.1508746  1.0000000 6.497874
## 5 {asset.assets.variety.P - Other} => {attribute.integrity.variety.Alter behavior} 0.1508590  0.9998968 6.480151
## 6 {asset.assets.variety.P - Other} => {actor.external.variety.Unknown}             0.1360769  0.9019203 2.079229
## 7 {asset.assets.variety.P - Other} => {victim.employee_count.Large}                0.1265752  0.8389428 1.145942
## 8 {asset.assets.variety.P - Other} => {victim.industry2.92}                        0.1270736  0.8422465 1.144683
## 9 {asset.assets.variety.P - Other} => {victim.orgsize.Large}                       0.1267465  0.8400785 1.137618
