### ISSUE TITLE
Why only 1 item on the right-hand-side of the rules?

### ISSUE THREAD

**Issue by leih123** [mhahsler/arules#18]
Dear Michael,

May I know why arules only generate rules with only 1 item on the right-hand-side? I have seen you have answered in

http://r.789695.n4.nabble.com/how-to-change-number-of-itemes-appeare-in-right-hand-side-of-the-rule-with-apriori-in-R-arules-td1559955.html

But do you mind to explain a bit more? If only rules with 1 item on the right-hand-side are generated, does it mean a lot of rules will be neglected (rules with >1 item on the right-hand-side) and also associations/patterns between items? 

Is a rule with more than 1 item on the RHS producing less value (less useful) than the rules with only 1 item on the RHS so it can be neglected?

Many thanks for your help.

**Comment by mhahsler** [comment]
You do not loose much information. It is literally just how most algorithms are implemented.

**Comment by leih123** [comment]
Ya, I found the full explanation on

http://www.borgelt.net/doc/apriori/apriori.html#conseq

Thanks anyway
