### ISSUE TITLE
Access/get value from sequence

### ISSUE THREAD

**Issue by drghifari** [mhahsler/arules#19]
I use arulesSequences and i want to access/get value from sequence every levels, for example:

`x <- read_baskets(file.choose(), info = c("sequenceID","eventID","SIZE"))`
`as(x,"data.frame")`
`s0 <- cspade(x, parameter = list(support = 0, maxsize = 5, maxlen = 5))`
`seq = as(s0, "data.frame")`

variable `seq` returned this:

>  1                          <{257}> 0.02777778
> 2                           <{259},{305}> 0.02777778
> 3                           <{259},{305}> 0.02777778
> 4                           <{259},{305}> 0.02777778
> 5                           <{259},{305}> 0.02777778
...
...
...

> 27                   <{292},{305}> 0.02777778
> 28                   <{293},{305}> 0.02777778
> 29             <{292},{293},{305}> 0.02777778
> 30             <{290},{293},{305}> 0.02777778
> 31             <{259},{293},{305}> 0.02777778
> 32       <{290},{292},{293},{305}> 0.02777778
> 33       <{259},{292},{293},{305}> 0.02777778

i want to get the first and last value of sequence per levels, something like this:
1 : first = last = 257
2 : first = 259, last = 305
29 : first = 292, last = 305
33 : first = 259, last = 305

is that possible?

**Comment by mhahsler** [comment]
Hi, 

this is for arules and not arulesSequences. You should send your question with an reproducible example to the R-help mailing list ([https://www.r-project.org/mail.html](https://www.r-project.org/mail.html)).

To get the information you want, consult the man page for sequence, i.e., `? sequence`. The sequence data structure is somewhat complicated and you can have several subsequences, which you do not have in your example. I am not sure what you want as the result in such a case.
