### ISSUE TITLE
Can't coerce to transaction using as (df, "transactions") when executed with Rscript

### ISSUE THREAD

**Issue by nirsisense** [mhahsler/arules#20]
Hi,
I'm trying to run the following script:
data <- list(
  c("a","b","c"),
  c("a","b"),
  c("a","b","d"),
  c("b","e"),
  c("b","c","e"),
  c("a","d","e"),
  c("a","c"),
  c("a","b","d"),
  c("c","e"),
  c("a","b","d","e")
)
as(data, "transactions")

through command line Rscript and get an error:
Error: could not find function "as"
Execution halted

**Comment by lordbitin** [comment]
Ensure that the dependencies of the arules package are loaded. `as` is a function from the pacjage "methods"

**Comment by nirsisense** [comment]
What are the dependent package I need to load?
I tried load "methods"
library("arules")
library("methods")
data <- list(
  c("a","b","c"),
  c("a","b"),
  c("a","b","d"),
  c("b","e"),
  c("b","c","e"),
  c("a","d","e"),
  c("a","c"),
  c("a","b","d"),
  c("c","e"),
  c("a","b","d","e")
)
trans <- as(data, "transactions")
 still fails in Rscript but runs fine in RStudio

**Comment by lordbitin** [comment]
Hmmmm the same lines of code are working for me, both in RStudio and RScript, event without loading "methods" explicitly...Do you have any other possible packages in the environment that could overwrite the definition of the `as` function ? What OS and R version are yoo using?

Also, try to reinstall the package with `install.packages("arules", dependencies=T)`

**Comment by mhahsler** [comment]
@nirsisense is correct. This has nothing to do with arules. You need to explicitly load methods when you use Rscript.

**Comment by nirsisense** [comment]
ok, thanks. It works now
