### ISSUE TITLE
Error in transactions-class documentation?

### ISSUE THREAD

**Issue by lordbitin** [mhahsler/arules#21]
Hi,

I think there is a simple error in the documentation of "transactions-class" when it says:

`coerce
signature(from = "matrix", to = "transactions"); produces a transactions data set from a binary incidence matrix. The row names are used as item labels and the column names are stores as transaction IDs.`

From what I can see in my experiments, rows represent transactions and columns represent items.

Regards,
Víctor

**Comment by mhahsler** [comment]
Thanks for reporting this error. It is now fixed in the development version. The fix will be part of the next release.
