### ISSUE TITLE
apriori code with appearance class

### ISSUE THREAD

**Issue by sagar-m** [mhahsler/arules#28]
Hi:

Was wondering how I could look for a particular word in RHS of appearance class in the apriori code.

rulesD<-apriori(data = txn, parameter=list(supp=0.0005,conf = 0.01), 
                appearance = list(default="lhs",rhs = grep("DATE|DATES", rhs, value = TRUE)),
                control = list(verbose=F))

Here I need a list of products on RHS that contains the word "DATE" or "DATES".
rhs = grep("DATE|DATES", rhs, value = TRUE)) in the code is resulting in error.

Following the below example:

rules<-apriori(data=dt, parameter=list(supp=0.001,conf = 0.8), appearance = list(default="lhs",rhs="Banana"), control = list(verbose=F))

Only the products that only contains "BANANA"is returned. However, "ORGANIC BANANA" is not returned in RHS.

Sorry if this is a simple question! :) Searched the cran doc, did not find a solution.

Thank you for your help.

**Comment by mhahsler** [comment]
I think you need to do something like `rhs = grep("DATE|DATES", itemLabels(rxn), value = TRUE)`.

**Comment by sagar-m** [comment]
Thank you.
