### ISSUE TITLE
ERROR in apriori parameter: appearance

### ISSUE THREAD

**Issue by sjain777** [mhahsler/arules#3]
Hi, when I train the model as follows:

traintrans <- as(traindata.data.frame, "transactions") 
rules <- apriori(traintrans, parameter = list(supp=0.001, minlen = 2, maxlen=5, conf = 0.5, target = "rules")
             , appearance = list(rhs = cnames))

where cnames <- colnames(traindata.data.frame)[7:9], that is, I would like to train the rules only for recommendations  from the list "cnames", why do some extra recommendations also trickle in the resulting output? Is not the parameter "appearance" supposed to control which set of values one is interested in getting recommendations for? 

Thanks!

**Comment by mhahsler** [comment]
Here is an example from ? APappearance

## find only rules with small or large income in the right-hand-side.
rules <- apriori(Adult, parameter = list(support=0.2, confidence = 0.5), 
  appearance = list(rhs = c("income=small", "income=large"),
  default="lhs"))

I think the default ="lhs" is important.

**Comment by sjain777** [comment]
yes, that worked, thanks!
