### ISSUE TITLE
Executing head() or tail() on empty rule set returns error

### ISSUE THREAD

**Issue by cornejom** [mhahsler/arules#31]
Executing head(x) or tail(x) on a rules object having no rules results in error message "Error in slot(x, s)[i] : subscript out of bounds".

Error does not occur with arules::sort().

Using arules 1.5-0 on R 3.3.3

**Comment by mhahsler** [comment]
I cannot reproduce the error with the current version of arules. Can you update to the latest version of arules and try again. If the problem persists, then I would need some data and code that reproduce the problem.

**Comment by cornejom** [comment]
I've updated to arules 1.5-3 and still get the error (on R 3.3.3).   

```R
data("Adult")
rules <- apriori(Adult, parameter = list(supp = 0.98))
length(rules) #Should be zero.
head(rules)
```
Console output of above is **Error in slot(x, s)[i] : subscript out of bounds**

**Comment by mhahsler** [comment]
Thank you for the example. I can confirm this as a bug.

**Comment by mhahsler** [comment]
The bug is now fixed in the development version on Github. The fix will be part of the next service release (1.5-4).
