### ISSUE TITLE
Error when using Rscript - should "arules" depend on "methods"?

### ISSUE THREAD

**Issue by lciti** [mhahsler/arules#33]
After getting a strange error

        Error in validObject(.Object) : 
          invalid class “ngCMatrix” object: Not a valid 'Mnumeric' class object

when using `random.transactions`, I realised that the error is due to the fact that `Rscript` does not load `methods` by default.

Minimal Working Example:

        R -e 'library("arules"); random.transactions(5, 5)'

works like a charm, while `Rscript` thorws an error:

        Rscript -e 'library("arules"); random.transactions(5, 5)'
        ...
        Error in validObject(.Object) : 
          invalid class “ngCMatrix” object: Not a valid 'Mnumeric' class object

A temporary fix is to run `Rscript` as follows:

        Rscript --default-packages=methods -e 'library("arules"); random.transactions(5, 5)'

Another solution is to add `library("methods")` in the code before importing `arules`.

Is there a better solution? Can the `arules` package made robust against this issue?

**Comment by mhahsler** [comment]
This is a good question. The reason for this behavior is `Rscript` (see: [rdocumentation](https://www.rdocumentation.org/packages/utils/versions/3.4.1/topics/Rscript)):

> The default for Rscript omits methods as it takes about 60% of the startup time.

`arules` imports methods correctly and this needs to be addressed at the R level. Sorry for the inconvenience.

**Comment by nmani1191** [comment]
I am also faced the same issue and adding library("methods") in the code before importing arules works.
