### ISSUE TITLE
FpGrowth?

### ISSUE THREAD

**Issue by stepthom** [mhahsler/arules#35]
Hi,

Are there any plans for including the FP Growth algorithm?

**Comment by mhahsler** [comment]
No time. Maybe a volunteer could create a separate package?

**Comment by nadiadwiandriani** [comment]
please help me to my task about fpgrowth,.

**Comment by mytarmail** [comment]
This algorithm is very very very very much needed There is no good implementation in R

**Comment by mhahsler** [comment]
FpGrowth is now available via fim4r.
