### ISSUE TITLE
Discretize using frequency

### ISSUE THREAD

**Issue by noeliarico** [mhahsler/arules#36]
Hi everyone,

I'm trying to use the `discretize` function. Given the following vector:

```
nums <- c(rep(1,7), 
          rep(2,3),
          rep(3,4),
          rep(4,5),
          rep(5,9),
          rep(6,10),
          rep(7,8),
          rep(8,1),
          rep(9,9),
          rep(10,4))
> nums
[1]  1  1  1  1  1  1  1  2  2  2  3  3  3  3  4  4  4  4  4  5  5  5  5  5  5  5  5
[28]  5  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  8  9  9  9  9  9  9  9
[55]  9  9 10 10 10 10
```

When I use the code `table(discretize(nums, "frequency", categories=6))` I get the output below

```
[ 1, 3) [ 3, 6)       6       7 [ 8,10)      10 
     10      18      10       8      10       4 
```

Nevertheless, I was expecting 6 categories of frequency 10. Am I misunderstanding something?

Thank you in advance,
Noelia

**Comment by mhahsler** [comment]
Given the data you cannot get exactly equal groups. For example, 3 and 4 add up to only 9 elements. I am working on a new version of discretize which will do a somewhat better job, balancing group sizes for the method frequency.
