### ISSUE TITLE
very few scores from interestsMeasure

### ISSUE THREAD

**Issue by naarkhoo** [mhahsler/arules#37]
I can see there is a long list of metrics/scores to calculate additional interest measures however, by default (by not setting the "measure" argument in the interestMeasure function, only 3 or 4 are calculated).

Basically, I am interested in calculating "certainty" which is on the list, but the function returns an error 

_"Error in interestMeasure(r, measure = c("certainty"), trans = subscription.trans) : 
  Value 'certainty' is an invalid measure for itemsets."_

This is regardless of using "apriori" or "eclat".

Thanks,

**Comment by mhahsler** [comment]
Hi, many measures are defined for rules, not only a few for itemsets. Since you aupply itemsets, it only calculates the few appropriate measures.
