### ISSUE TITLE
discretize function not working when NA in data vector 

### ISSUE THREAD

**Issue by yarik1988** [mhahsler/arules#38]
In previous version of discretize it works well on vectors with NA available. This is not a big issue, but in general this function works differently than the old one. On the same data it does not allow me to use same number of bins, tells to decrease it. So I invoked and use old discretize and cut2 function

**Comment by mhahsler** [comment]
Note that discretize now used equal "frequency" as the default. The development version on github now handles NAs correctly again (will be part of the next release). The previous discretization was faulty and that is why the results in the new version are different. Please let me know if you have an example where it produces incorrect/strange results.

Thanks!

**Comment by mhahsler** [comment]
NA problem is fixed in version arules 1.6-1.
