### ISSUE TITLE
interpretation the plot of association rules(MBA) in R

### ISSUE THREAD

**Issue by jasperDD** [mhahsler/arules#40]
I performed association Rules

    trans <-  read.transactions("C:/Users/synthex/Downloads/Groceries.csv", format = 'basket', sep = ',')
    rules <- apriori(trans, parameter = list(supp = 0.001, conf = 0.8))
    rules <- apriori(trans, parameter = list(supp = 0.001, conf = 0.8,maxlen=3))
    plot(rules,method="graph",engine='interactive',shading=NA)

Then i got this plot

  https://i.stack.imgur.com/3jr7x.jpg

What does mean the  red circles and is it possible **to give lable them**?

mydat

    structure(list(chocolate = structure(c(9L, 13L, 1L, 8L, 16L, 
        2L, 14L, 11L, 7L, 15L, 17L, 5L, 10L, 4L, 3L, 6L, 2L, 18L, 12L
        ), .Label = c("bottled water", "canned beer", "chicken,citrus fruit,tropical fruit,root vegetables,whole milk,frozen fish,rollsbuns", 
        "chicken,pip fruit,other vegetables,whole milk,dessert,yogurt,whippedsour cream,rollsbuns,pasta,soda,waffles", 
        "citrus fruit,pip fruit,root vegetables,other vegetables,whole milk,cream cheese ,domestic eggs,brown bread,margarine,baking powder,waffles", 
        "frankfurter,citrus fruit,onions,other vegetables,whole milk,rollsbuns,sugar,soda", 
        "frankfurter,rollsbuns,bottled water,fruitvegetable juice,hygiene articles", 
        "frankfurter,sausage,butter,whippedsour cream,rollsbuns,margarine,spices", 
        "fruitvegetable juice", "hamburger meat,other vegetables,whole milk,curd,yogurt,rollsbuns,pastry,semi-finished bread,margarine,bottled water,fruitvegetable juice", 
        "meat,citrus fruit,berries,root vegetables,whole milk,soda", 
        "packaged fruitvegetables,whole milk,curd,yogurt,domestic eggs,brown bread,mustard,pickled vegetables,bottled water,misc. beverages", 
        "pickled vegetables,coffee", "root vegetables", "tropical fruit,margarine,rum", 
        "tropical fruit,pip fruit,onions,other vegetables,whole milk,domestic eggs,sugar,soups,tea,soda,hygiene articles,napkins", 
        "tropical fruit,root vegetables,herbs,whole milk,butter milk,whippedsour cream,flour,hygiene articles", 
        "turkey,pip fruit,salad dressing,pastry"), class = "factor")), .Names = "chocolate", class = "data.frame", row.names = c(NA, 
        -19L))

**Comment by mhahsler** [comment]
The unlabeled circles are the rules. Please use stackoverflow for questions so other users can also find answers.
