### ISSUE TITLE
Why apriori telling me attempt to apply non-function

### ISSUE THREAD

**Issue by derekrdm** [mhahsler/arules#41]
I'm trying to do a market basket analysis using arules package. However, when I was using the apriori algorithm, R reported the following message.

```
dt <- split(deviceshowlist$prog_title, deviceshowlist$device_id)
dt2 <- as(dt,"transactions")
rules <- apriori(dt2, parameter = list(support = 0.01, confidence = 0.05, minlen=2))
```

> Apriori
> Parameter specification:
> Error in print.default(parameter) : attempt to apply non-function
> 

I looked at my transaction data structure and the function of apriori. It seems that there's nothing wrong. Kindly hope that someone ran into the similar question before and could help me with it.

Thanks

**Comment by mhahsler** [comment]
Hi! I need enough code/data to reproduce the problem. Also, I need the output of sessionInfo().
