### ISSUE TITLE
License types for datasets

### ISSUE THREAD

**Issue by Armour** [mhahsler/arules#42]
Hi Michael,

What's the license type for your datasets? is that under public domain? I found your groceries dataset in this [repo](https://github.com/stedy/Machine-Learning-with-R-datasets) and it says it's under public domain, so I just want to double check this with you, thanks!

A reference website for common license types [here](https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets)

**Comment by mhahsler** [comment]
The arules package and all its content is licensed under GPL-3.
