### ISSUE TITLE
parameter appearance in apriori

### ISSUE THREAD

**Issue by amorabonilla** [mhahsler/arules#47]
I am not sure if there is an error in parameter appearance (or I don not understand the meaning).

I execute: 

******
# Download dataset from
# http://www.rdatamining.com/data/titanic.raw.rdata
# Save in local directory of R
load("./titanic.raw.rdata")
library(arules)
rules <- apriori(titanic.raw, control = list(verbose=F),
                 parameter = list(supp=0.002, conf=0.01),
                 appearance = list( rhs=c("Survived=Yes"),
                                    lhs=c("Class=1st", "Class=2nd", "Class=3rd",
                                          "Age=Child", "Age=Adult")))
inspect(rules)
# 12 rules

rules2 <- apriori(titanic.raw, control = list(verbose=F),
                 parameter = list(supp=0.002, conf=0.01),
                 appearance = list( rhs=c("Survived=Yes"),lhs=c("Class=1st")))
inspect(rules2)
# 2 rules
*****

My concern is about. rules1 has 12 rules with some of the attributes in:
--->  lhs=c("Class=1st", "Class=2nd", "Class=3rd",
                                          "Age=Child", "Age=Adult")

But with the second call to apriory I put a less restrictive set of conditions to apriori:
--->,lhs=c("Class=1st")

My question is why the second call generate less rules? 

For instance in the first order the rule
[8]  {Class=1st,Age=Child} => {Survived=Yes} 0.002726034 1.0000000 
is generated

But in the second order this rule is not generated. And it has Class=1st on the left. 

Could you help me?

Thank you very much in advance

ANGEL MORA BONILLA
University of Málaga, Spain

**Comment by mhahsler** [comment]
Unfortunately, the specification of templates is somewhat tricky for APRIORI. From `? APappearance`

```
‘lhs’, ‘rhs’, ‘both’, ‘items’, ‘none’: character vectors giving
          the labels of the items which can appear in the specified
          place (rhs, lhs or both for rules and items for itemsets).
```

This does not mean that the LHS has to contain the specified item and also can contain other items. LHS can only contain the specified items. This is why the rule above is in set 1, but not in set 2.
