### ISSUE TITLE
Rules object-size increases upon using subset or sort: possible memory leak? 

### ISSUE THREAD

**Issue by sjain777** [mhahsler/arules#5]
I noticed that the object size increased for the rules after performing any action on it, like subsetting the RHS or sorting. For example:  

object.size(arulesModel) 
#16908112 bytes   # ~ 17 MB  

arulesModelSubset <- subset(arulesModel, subset = rhs %in% cnames) 
#object.size(arulesModelSubset) #49910224 bytes   # 50 MB compared to 17 MB above  

arulesModelSorted <- sort(arulesModel, by = "lift") 
object.size(arulesModelSorted) 
#50946536 bytes   # 51 MB compared to 17 MB above. 

Is this expected or is there possibly a memory leak? 
Thanks!

**Comment by mhahsler** [comment]
I just checked and it seems that the memory problem comes from  how R handles data.frames with 0 column... I need to fix this.

**Comment by sjain777** [comment]
ok, thanks!

**Comment by mhahsler** [comment]
This bug should be fixed in the new release.

**Comment by sjain777** [comment]
yes, I verified with the _subset_ method on the _apriori_ object, and the memory of the resulting object does not double any more with the new release (arules: 1.4-0). Thanks much for fixing the problem!
