### ISSUE TITLE
Several inconsistencies regarding the "ralambrodrainy" measure of interest

### ISSUE THREAD

**Issue by andreijl** [mhahsler/arules#54]
The measure referred to as "ralambrodrainy" seems to be a spelling mistake regarding the names of the authors that wrote the paper 
*Diatta, J., Ralambondrainy, H., & Totohasina, A. (2007). Towards a Unifying Probabilistic Implicative Normalized Quality Measure for Association Rules. Studies in Computational Intelligence, 237–250. doi:10.1007/978-3-540-44918-8_10*".
During investigating the correlation between rankings of different measures I found that this measure also has a negative or no correlation with most other measures . Especially confidence is highly negatively correlated.
This makes me think that there might be something wrong with the implementation.

**Comment by mhahsler** [comment]
Thank you for reporting this typo. It is now fixed on GitHub. Have a look at the definition of the measure (https://michael.hahsler.net/research/association_rules/measures.html#ralambondrainy). This should explain why you found a neg. correlation.
