### ISSUE TITLE
something wrong with the read.transaction function

### ISSUE THREAD

**Issue by Sisi-Wiciel** [mhahsler/arules#55]
When I use the read.transaction function with the format='single', and set the encoding='UTF-8', the text still can't read in the right encoding. Then I read the source code , I found that when the format='single', the parameter ‘encoding’ wasn't used.

The source code in file--read_write.R line101
` entries <- scan(file = file, sep = sep, quote = quote, what = what, flush = TRUE,
                    quiet = TRUE, skip = skip)`
Maybe it should be like this?
 `entries <- scan(file = file, sep = sep, quote = quote, what = what, flush = TRUE,
                    quiet = TRUE, skip = skip, encoding=encoding)`

**Comment by mhahsler** [comment]
Thank you for the bug report. This is now fixed in the development version on GitHub. Please test.
