### ISSUE TITLE
arules: transactions-class

### ISSUE THREAD

**Issue by sjain777** [mhahsler/arules#6]
Hi, the following example is available for coercing a data.frame into transactions object when the TransactionId and Items are provided: 
`## example 4: creating transactions from a data.frame with 
## transaction IDs and items 
a_df3 <- data.frame(
  TID = c(1,1,2,2,2,3), 
  item=c("a","b","a","b","c", "b")
  )
a_df3
trans4 <- as(split(a_df3[,"item"], a_df3[,"TID"]), "transactions")
trans4
inspect(trans4)
`
However, when I try to apply the same to a data.frame that has additional columns, I get error:
    Error in asMethod(object) : can coerce list with atomic components only

My example is: 
`a_df3` <- data.frame(TID = c(1,1,2,2,2,3),  item=c("a","b","a","b","c", "b") , column2 = c("Mon", "Wed", "Mon", "Tue", "Fri", "Mon"))
trans4 <- as(split(a_df3[,c("item", "column2")], a_df3[,"TID"]), ``"transactions")`
    Error in asMethod(object) : can coerce list with atomic components only

Is there a method available to do the above with multiple columns (factor/logical)? In my application, if I first use "dcast" to create a WIDE table with unique TID values per row and then use only the data.frame without the TID column to convert it into a "transactions" object following your example 3 (a_df), then my data.frame size becomes too large (up to 5-7 GB). So I was hoping to create the "transactions" object required for "apriori" directly from my multiple-columns LONG table as shown above.  

Thanks for any feedback!

**Comment by mhahsler** [comment]
How do the transaction that you would expect look like? You can only have one set of items.

**Comment by sjain777** [comment]
Thanks for your looking into this. Here is an small example:
`TId = c(1, 2, 3, 4, 5)
Country = c("US", "India", "Brazil", "US", "Switzerland")
IncomeClass = c("Medium", "Medium", "High", "High", "Medium")
df1 <- data.frame(TId, Country, IncomeClass)

TId = c(1, 1, 2, 2, 3, 3, 4, 4, 5)
Products = c("Milk", "Strawberry", "Milk", "Tea", "Milk", "Coffee", "Banana", "Chocolate",  "Cheese")
df2 <- data.frame(TId, Products)

df3 <-  merge(df1, df2, by = "TId", all.x = TRUE)
`
I would like to do the following: 
    trans5 <-  as(split(df3[, c(2:3)], df3[, "Tid"] ), "transactions")
such that trans5 looks like the following: 
trans5: 
TId        items
1           {Country=US, IncomeClass=Medium,Milk,Strawberry}
2           {Country=India, IncomeClass=Medium,Milk, Tea}
3           {Country=Brazil, IncomeClass=High,Milk, Coffee}
4           {Country=US, IncomeClass=High,Banana, Chocolate}
5           {Country=Switzerland, IncomeClass=Medium,Cheese}

Thanks,
Supriya

**Comment by mhahsler** [comment]
The is more an R question than an arules question. You just need to construct your items so you have a single set:

# create a single set
> df3_recoded <- data.frame(TId = rep(df3$TId, times = 3), items = c(paste0("Country=", df3$Country), paste0("IncomeClass=", df3$IncomeClass), as.character(df3$Products)))
> df3_recoded
   TId               items
1    1          Country=US
2    1          Country=US
3    2       Country=India
4    2       Country=India
5    3      Country=Brazil
6    3      Country=Brazil
7    4          Country=US
8    4          Country=US
9    5 Country=Switzerland
10   1  IncomeClass=Medium
11   1  IncomeClass=Medium
12   2  IncomeClass=Medium
13   2  IncomeClass=Medium
14   3    IncomeClass=High
15   3    IncomeClass=High
16   4    IncomeClass=High
17   4    IncomeClass=High
18   5  IncomeClass=Medium
19   1                Milk
20   1          Strawberry
21   2                Milk
22   2                 Tea
23   3                Milk
24   3              Coffee
25   4              Banana
26   4           Chocolate
27   5              Cheese

# we do not want duplicate entries
> df3_recoded <- unique(df3_recoded)

# create transactions
> trans <- as(split(df3_recoded$items, df3_recoded[, "TId"] ), "transactions")
> inspect(trans)
  items                 transactionID
1 {Country=US,                       
   IncomeClass=Medium,               
   Milk,                             
   Strawberry}                      1
2 {Country=India,                    
   IncomeClass=Medium,               
   Milk,                             
   Tea}                             2
3 {Coffee,                           
   Country=Brazil,                   
   IncomeClass=High,                 
   Milk}                            3
4 {Banana,                           
   Chocolate,                        
   Country=US,                       
   IncomeClass=High}                4
5 {Cheese,                           
   Country=Switzerland,              
   IncomeClass=Medium}              5


I am sure you can do this prettier using plyR or reshape.

**Comment by sjain777** [comment]
ok. Thanks much for showing the details above.
