### ISSUE TITLE
Bug: RStudio generates X ammount of Rules, Knited Document has Y

### ISSUE THREAD

**Issue by gustavom2998** [mhahsler/arules#60]
I have been using this package to produce rules with very low support. In order to not run out of memory, I have been using a maxtime parameter of 100. Without using Cache, and after deleting all the files generated by knitting (things that I have found that make this bug happen more often), I will run the code in RStudio and get say 50 rules. When Knitting the file, The same chunk of code will produce more rules (Say 60), as if it continues from the first run. I have tried cleaning recycling bin, deleting temp files, cleaning R Environment,  and every once in a while it will work and produce the same amount of rules. More often than not, a different amount of rules are generated for the same chunk. I think the issue is related to the knitting process continuing from where the last session stopped, or a memory leak as suggested by the documentation, even though I don't force the execution to stop.

**Comment by mhahsler** [comment]
Please share some code that shows this problem with me then I can try to debug the issue.

Regards,
-MFH

**Comment by gustavom2998** [comment]
I have recreated the problem with a very small amount of code since it originally happened to me using very large code (5k+ lines). I have uploaded a repository ([link](https://github.com/gustavom2998/Bug_Arules))with the code + data used to produce the error, since a large amount of data is necessary to reproduce the error (I believe). Here are some screenshots:

![Rstudio1](https://user-images.githubusercontent.com/42518882/88807760-84ae6300-d188-11ea-8cf9-addd6c70124a.PNG)

![Rstudio2](https://user-images.githubusercontent.com/42518882/88807728-7b24fb00-d188-11ea-971a-b9200f8f585e.PNG)

![knitted](https://user-images.githubusercontent.com/42518882/88807746-824c0900-d188-11ea-95aa-7038b116f80a.PNG)

**Comment by mhahsler** [comment]
I think I do not understand the question completely. When you say knit multiple times, do you mean pushing the knit button in RStudio several times, and every time it knits, the number of rules increases (doubles) every time?

The code that you sent me creates two rule sets. You use different minsupport and lhs and thus we would expect a different result.

**Comment by gustavom2998** [comment]
By knitting multiple times I mean to Knit the code once, make a few changes to text (not code), then knit it again. I expected that this would not change the rules generated, but it seems to change. Unless I am confused by how the package works (which could very well be true), If I produce association rules today, or tomorrow, or next year, if the parameters are the same, the rules generated should also be the same, since the rule generation process isn't random. I also expect that If I run the code inside RStudio, or Knit the code to a document, the rules generated should be the same.

**Comment by mhahsler** [comment]
Since you limit the time it could give different results depending on the load of your system. If you want predictable results, then you could limit the length of the rules using maxlen.

**Comment by gustavom2998** [comment]
Very strange, since knitting the document should be a more intense task (in my idea), however, the knitted rules are generally larger than the ones generated by running the code in R. No chance that it's some kind of memory leak? By checking the length of the rules, it seems that the knitted version continues producing rules from where the rules generated in R stopped since it continues producing rules of larger length, as If I had some kind of cache turned on (even though in my original code I specified it as off). I might be valid to add to the CRAN documentation (or wherever suitable) that the time limit could cause problems with knitr.

**Comment by mhahsler** [comment]
A memory leak is quite unlikely given the amount of memory leak testing that is done on R packages. Have you tried to remove the time limit and limit maxlen. I think this should solve the issue.

**Comment by gustavom2998** [comment]
Since the number of transactions is so large (500K+) and the support so low, removing the time-limit definition would generate 0 rules. If by maxlen you mean by limiting the number of items, that would change most of the results that I have already produced (since most cases appear to stop mid-rule generation, like the second chunk were it genearted 42 rules of size 5, then when knited generated 40 of size 5 and the other 2 appear to have been increased to size 6) and wouldn't really be a solution for me. If there is a parameter that limits the a maximum ammount of rules to generate, it might help me, but I looked at the CRAN documentation and found nothing.

**Comment by mhahsler** [comment]
There is no parameter to limit the number of rules. The timeout check is only done once for each size (number of items), so what you see is that in your second run it had enought time to start size 6 while in the first one it did not. Setting maxlen to 5 (or 6) and removing the timeout should work.

**Comment by gustavom2998** [comment]
Thanks for your time and help. I appreciate it very much!
