### ISSUE TITLE
Error in transactions(AdultUCI) : could not find function "transactions"

### ISSUE THREAD

**Issue by petamva** [mhahsler/arules#65]
Hey! I am using V1.6-8 and i am following the examples on the documentation. I get the stacktrace on the title when i attempt to run:
Adult <- transactions(AdultUCI)
However S4 coercion works:
trans1 <- as(AdultUCI,  "transactions")

Any help would be appreciated!
Thanks
Peter

**Comment by mhahsler** [comment]
transactions() is a new function in 1.6-8. I just reinstalled this last version from CRAN and it works for me (with appropriate warnings).

Type: `sessionInfo()` 

Make sure it says 1.6-8 in:
```
...
other attached packages:
[1] arules_1.6-8 Matrix_1.3-3
```

**Comment by petamva** [comment]
You are right. Even though i have the latest version installed in my system's R distribution, i was trying to run the command in an Anaconda virtual environment which supports v1.6_3. Thanks!
Closing issue.
