### ISSUE TITLE
issue when aggregating items

### ISSUE THREAD

**Issue by javiercoh** [mhahsler/arules#66]
Hi, I'm using arules `1.6.8`. For this issue I have [added a repo](https://github.com/javiercoh/test-arules-h.git) to reproduce the results that includes both code and data.

I have identified a transaction for a given customer that contains certain items that belong to an aggregate category_id = "IP0402-LEUDANTES CO" as shown here:

` 
    customer_id customer_size sku_nbr  avg_ROS     sku_id         category_id
163 C1020395696       4813177      40 120329.4 AD01020009 IP0402-LEUDANTES CO
    sku_amount sku_qty top_skus city_id
163   142684.2       1        4       3`

However, the resulting aggregated transactions dataset for that transaction does not include "IP0402-LEUDANTES CO" 

```
CR0201-LIQ ARTIF CO,               
     CR0202-POL ARTIF CO,               
     CR0203-POLV LACA CO,               
     IA0301-MOLDES CO,                  
     IA0305-MANG-BOQ CO,                
     IH0505-PROD PAST CO,               
     IP0401-PREMEZCLAS CO,              
     IP0404-TOPPINGS CO,                
     IP0405-RELL-COBER-CO,              
     IP0406-HUMECT CO,                  
     SA0701-SALSAS CO,                  
     SA0702-ADEREZOS CO,                
     SB0106-SABORES CO}      C1020395696
```

Any idea what may be causing this?

**Comment by mhahsler** [comment]
Your repo only contains the data. Please post the code that you use to aggregate the data and reproduce your results.

**Comment by javiercoh** [comment]
> Your repo only contains the data. Please post the code that you use to aggregate the data and reproduce your results.

oops, thanks. just uploaded it

**Comment by mhahsler** [comment]
Your category id in
    
    .GlobalEnv$dataset@itemInfo <- data.frame(labels = category$sku_id, category_id = category$category_id)

is numeric, but it needs to be character/factor.

It would be better to follow the example in `? addAggregate`.

**Comment by javiercoh** [comment]
> Your category id in
> 
> ```
> .GlobalEnv$dataset@itemInfo <- data.frame(labels = category$sku_id, category_id = category$category_id)
> ```
> 
> is numeric, but it needs to be character/factor.
> 
> It would be better to follow the example in `? addAggregate`.

Thanks @mhahsler. However to me it seems that the problem is in the addAggregate function. If I run str(.GlobalEnv$dataset@itemInfo) before applying addAggregate I do get a `chr` type for category_id.

After applying addAggregate, somehow it changes to numeric as you noticed.

Also would add that I do get correct results when I create the aggregate transaction set using 

`category <- .GlobalEnv$df %>% select(customer_id, category_id) %>% distinct()  
.GlobalEnv$dataset <- as(split(category$category_id, category$customer_id), "transactions")`

**Comment by mhahsler** [comment]
This is what I get when I run your code:

```
> category <- df %>% select(sku_id, category_id) %>% distinct()  # https://stackoverflow.com/questions/55998277/r-how-to-incorporate-categories-of-item-set-in-transactions-data
> category
        sku_id category_id
1   IA03080005   11.928638
2   IA03080005   11.457032
3   IA03080005   11.397616
4   IA03050158    9.647304
...
```

`category_id` looks like a number to me.
