### ISSUE TITLE
What is transIdenticalToItemsets? 

### ISSUE THREAD

**Issue by galadrielbriere** [mhahsler/arules#67]
Hi,
I've been using Arules' apriori algorithm to find maximally frequent itemsets in my data. 

```
rules1 =  apriori(trans1, parameter = list(target = "maximally frequent itemsets"))
inspect(head(rules1))
```
> items                 support     transIdenticalToItemsets count
> [1] {ds1_75072,ds1_67826} 0.004487323 0.003141126              20   
> [2] {ds1_78540}           0.011891407 0.002468028              53   
> [3] {ds1_81979,ds1_55902} 0.005833520 0.002243662              26   
> [4] {ds1_75072,ds1_77311} 0.007628450 0.001570563              34   
> [5] {ds1_81979,ds1_50293} 0.004711689 0.001346197              21   
> [6] {ds1_81979,ds1_93779} 0.003365492 0.001346197              15 

I don't understand what is the transIdenticalToItemsets measure, and I could not find anything about it in the documentation. Could someone explain ?

**Comment by mhahsler** [comment]
Thank you for this bug report. The column is there accidentally. Please ignore it. It will be removed in the next release.
