### ISSUE TITLE
Apriori " Error in deparse1(call) : could not find function "deparse1" "

### ISSUE THREAD

**Issue by g-cloud9** [mhahsler/arules#71]
rules <- apriori(Groceries, parameter = list(support = 0.01, confidence = 0.2))
Apriori

Parameter specification:
 confidence minval smax arem  aval originalSupport maxtime support minlen maxlen target  ext
        0.2    0.1    1 none FALSE            TRUE       5    0.01      1     10  rules TRUE

Algorithmic control:
 filter tree heap memopt load sort verbose
    0.1 TRUE TRUE  FALSE TRUE    2    TRUE

Absolute minimum support count: 98 

set item appearances ...[0 item(s)] done [0.00s].
set transactions ...[169 item(s), 9835 transaction(s)] done [0.01s].
sorting and recoding items ... [88 item(s)] done [0.00s].
creating transaction tree ... done [0.01s].
checking subsets of size 1 2 3 4 done [0.00s].
writing ... [232 rule(s)] done [0.00s].
creating S4 object  ... done [0.00s].
Error in deparse1(call) : could not find function "deparse1"

**Comment by mhahsler** [comment]
Hi,

thank you for the bug report. The latest version of arules requires R 4.0.0, but I did not state that correctly in the DESCRIPTION file. I will fix this as soon as possble. Options are:

* Upgrade to the latest version of R
* Use the backport package.

Sorry for the inconvenience.

Regards,
-MFH
