### ISSUE TITLE
Discretize is not passing the dig.lab method to cut

### ISSUE THREAD

**Issue by LectronPusher** [mhahsler/arules#74]
https://github.com/mhahsler/arules/blob/3d008b726abef099c08c31a903bcf52e64befce9/R/discretize.R#L222
This is an oof.

**Comment by mhahsler** [comment]
Thank you for the bug report! The bug has been fixed in the development version on GitHub and will be part of the next release. You can install the fixed version in the meanwhile using:

```
install.packages("arules", repos = "https://mhahsler.r-universe.dev")
```
