### ISSUE TITLE
Least Contradiction Range incorrect

### ISSUE THREAD

**Issue by jhautala** [mhahsler/arules#76]
The correct range is [-∞,1]

I also want to mention that this is an amazing resource for association rule metrics. It is very thorough and I love the TOC!

**EDITED: original report had incorrect upper bound of ∞**

**Comment by mhahsler** [comment]
Hi, thank you for pointing this out. I did some research and found [-infty, 1]. How did you get to [-infty, infty]?

**Comment by jhautala** [comment]
Ahh, you're right; I got that range by... not proof-reading!

**Comment by mhahsler** [comment]
Thanks again. I have updated the page.
