### ISSUE TITLE
arulesSequences error with timeout

### ISSUE THREAD

**Issue by clairerichardsRN** [mhahsler/arules#79]
Greetings I'm getting the following error. I updated all packages and I still get this error. 
```
data(zaki)
> s0 <- cspade(zaki, parameter = list(support = 0,
                                 maxsize = 1, maxlen = 1),
               control   = list(verbose = TRUE))
```

parameter specification:
support : 0
maxsize : 1
maxlen  : 1

algorithmic control:
bfstype  : FALSE
verbose  :  TRUE
summary  : FALSE
tidLists : FALSE

preprocessing ...Error in system(command, flag, f, stdout, stderr, timeout) : 
  invalid 'timeout' argument

**Comment by mytarmail** [comment]
Hello!
I'm afraid you're in the wrong place.
arulesSequences it's a different package and a different developer
[https://github.com/cran/arulesSequences](url)

**Comment by mhahsler** [comment]
Hello!
I'm afraid you're in the wrong place.
arulesSequences it's a different package and a different developer

https://github.com/cran/arulesSequences
