### ISSUE TITLE
interestMeasure - mutualInformation - giving negative values

### ISSUE THREAD

**Issue by ddessommes** [mhahsler/arules#8]
Was using interestMeasure, and decide to sample some asymmetric measures with symmetric was surprised to see the Mutual Information (M) numbers come back negative based on the documentation on the arules pdf.

"mutualInformation", uncertainty, M (Tan et al., 2002)
Measures the information gain for Y provided by X.
**Range: [0, 1] (0 for independence)**

assuming it could be just a bug (i.e. remove the minus sign and that should be it)... FYI

Sample below:
> measures7 <- interestMeasure(rules_Arrest, 
+                             c("phi", "mutualInformation", "cosine",  "jaccard", "lift", "hyperLift"), #"leverage", "support", "gini", "hyperConfidence"),
+                             transactions = DPPD_trans1_Arrest)
> inspect(head(rules_Arrest))
  lhs                rhs                      support    confidence lift     
1 {ZipCode=75240} => {Division=North Central} 0.02027592 1.0000000   9.235521
2 {Sector=640}    => {Division=North Central} 0.02100753 1.0000000   9.235521
3 {Sector=110}    => {Division=Central}       0.02132107 1.0000000   8.181274
4 {ZipCode=75212} => {Sector=420}             0.02132107 0.9855072  40.997101
5 {ZipCode=75212} => {Division=SouthWest}     0.02142559 0.9903382   5.879960
6 {ZipCode=75208} => {Division=SouthWest}     0.02158236 0.9951807   5.908712
> head(measures7, n = 20)
          phi mutualInformation    cosine    jaccard      lift hyperLift
1  0.41284206      -0.307263353 0.4327340 0.18725869  9.235521  6.807018
2  0.42038123      -0.310908803 0.4404718 0.19401544  9.235521  6.931034
3  0.39553519      -0.285008230 0.4176524 0.17443352  8.181274  6.181818
4  0.93344676      -0.847975096 0.9349343 0.87553648 40.997101 22.666667
5  0.32658365      -0.214306327 0.3549388 0.12705299  5.879960  4.659091
6  0.32891311      -0.216503142 0.3571049 0.12806202  5.908712  4.693182
7  0.47310567      -0.353491059 0.4906198 0.24783684 11.486745  8.354167
8  0.09550435      -0.012162221 0.1752533 0.03071371  1.409442  1.315457
9  0.09428369      -0.011812036 0.1750450 0.03078283  1.402731  1.310345
10 0.43094164      -0.316088614 0.4512959 0.20366795  9.235521  6.918033
11 0.94651261      -0.869063673 0.9477856 0.89938398 39.246165 23.052632
12 0.94651261      -0.884808556 0.9477856 0.89938398 39.246165 23.052632
13 0.86713506      -0.752373996 0.8704477 0.75767918 32.655290 19.304348
14 0.44229206      -0.321755514 0.4629100 0.21428571  9.235521  6.937500
15 0.07797480      -0.007918385 0.1698410 0.03065275  1.323733  1.237389
16 0.09873251      -0.012415261 0.1810415 0.03277602  1.409442  1.320475
17 0.41578962      -0.295491763 0.4383589 0.19215855  8.244722  6.371429
18 0.68171238      -0.548458088 0.6910043 0.47748691 20.037696 13.411765
19 0.60163715      -0.471097334 0.6141427 0.37717122 15.827957 11.121951
20 0.34716814      -0.225250203 0.3761424 0.14148309  5.937325  4.750000
19 0.60163715      -0.471097334 0.6141427 0.37717122 15.827957 11.121951
20 0.34716814      -0.225250203 0.3761424 0.14148309  5.937325  4.750000
>

**Comment by mhahsler** [comment]
Thanks for this report. The bug is now fixed in the development version on github.
