### ISSUE TITLE
Difference between is.significant() and InterestMeasure() - with same method

### ISSUE THREAD

**Issue by ChantKatrjian** [mhahsler/arules#80]
Hello,
I have been using InterestMeasure(method = "fishersExactTest") and filtering out values less than 0.05. This approach however gives me different results compared to the logical is.significant(method = "fisher" with an alpha value of 0.05). Are these two tests the same? If not can someone please highlight what the difference is?
When I drop my value from 0.05 to something like 0.00000005 (for interestMeasure()) I get a more similar result as the is.significant() function with an alpha value of 0.05. 
If no one has had this issue I can provide an example of my input-output.

**Comment by mhahsler** [comment]
is.significant uses by default Bonferroni correction. Use adjust = "none" and then you should get the same result.

**Comment by ChantKatrjian** [comment]
Perfect.
